// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Creator = __t.object("Creator", {
  name: __t.string(),
  password: __t.string(),
});
export type Creator = __Infer<typeof Creator>;

export const Image = __t.object("Image", {
  creator: __t.string(),
  id: __t.u64(),
  data: __t.byteArray(),
  mimetype: __t.string(),
  uploadedAt: __t.timestamp(),
});
export type Image = __Infer<typeof Image>;

