// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCreatorReducer from "../add_creator_reducer";
import AddImageReducer from "../add_image_reducer";
import SayHelloReducer from "../say_hello_reducer";

export type AddCreatorParams = __Infer<typeof AddCreatorReducer>;
export type AddImageParams = __Infer<typeof AddImageReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;

